[package]
name = "aes-encryption"
version = "0.1.0"
edition = "2021"

[dependencies]
# 核心依赖
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
nb = "1.0"

# STM32F4 HAL
stm32f4xx-hal = { version = "0.19", features = ["stm32f407", "rt"] }

# 数学和信号处理
libm = "0.2"
micromath = "2.0"
num-traits = { version = "0.2", default-features = false }

# 时间和延时
embedded-time = "0.12"
fugit = "0.3"

# 数据序列化和存储
serde = { version = "1.0", default-features = false, features = ["derive"] }
postcard = "1.0"
heapless = { version = "0.8", features = ["serde"] }

# 通信协议
embedded-hal = "0.2"
embedded-hal-nb = "1.0"

# 显示和用户界面
embedded-graphics = "0.8"
ssd1306 = "0.8"

# 加密和安全
aes = "0.8"
sha2 = { version = "0.10", default-features = false }
hmac = { version = "0.12", default-features = false }
rsa = { version = "0.9", default-features = false, features = ["sha2"] }
rand_core = { version = "0.6", default-features = false }
chacha20poly1305 = { version = "0.10", default-features = false, features = ["heapless"] }

# 滤波和控制算法
pid = "4.0"

# Flash存储
embedded-storage = "0.3"

# 实时任务调度
rtic = { version = "2.0", features = ["thumbv7-backend"] }
rtic-time = "1.0"
rtic-monotonics = { version = "1.0", features = ["cortex-m-systick"] }

# 日志和调试
defmt = "0.3"
defmt-rtt = "0.4"

# CRC计算
crc = "3.0"

# UUID生成
uuid = { version = "1.0", default-features = false }

[features]
default = []
std = []

[[bin]]
name = "aes_basic"
path = "src/aes_basic.rs"

[[bin]]
name = "aes_cbc"
path = "src/aes_cbc.rs"

[[bin]]
name = "chacha20_poly1305"
path = "src/chacha20_poly1305.rs"

[[bin]]
name = "secure_storage"
path = "src/secure_storage.rs"

[profile.dev]
debug = 2
opt-level = "s"

[profile.release]
debug = 2
lto = true
opt-level = "s"
overflow-checks = false

# 目标平台配置
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "arm-none-eabi-gdb"
rustflags = [
  "-C", "linker=arm-none-eabi-ld",
  "-C", "link-arg=-Tlink.x",
]

# 链接器配置
[target.thumbv7em-none-eabihf]
runner = "arm-none-eabi-gdb"
rustflags = [
  "-C", "linker=arm-none-eabi-ld",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=--nmagic",
]

# 内存配置
[package.metadata.memory]
ram_start = 0x20000000
ram_size = 128K
flash_start = 0x08000000
flash_size = 1024K

# RTIC配置
[package.metadata.rtic]
backend = "thumbv7-backend"