[package]
name = "basic-controller"
version = "1.0.0"
edition = "2021"
authors = ["Industrial Team <industrial@example.com>"]
description = "基础工业控制器模板 - 通用PLC功能实现"
keywords = ["industrial", "controller", "plc", "automation", "template"]
categories = ["embedded", "no-std", "template"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/example/embedded-development"
readme = "README.md"
homepage = "https://example.com/basic-controller"
documentation = "https://docs.example.com/basic-controller"

[[bin]]
name = "basic-controller"
path = "src/main.rs"

[dependencies]
# 实时操作系统
rtic = { version = "2.0", features = ["thumbv7-backend"] }
rtic-time = { version = "1.0" }
rtic-monotonics = { version = "1.0" }

# 嵌入式核心库
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
embedded-hal = "1.0"
nb = "1.0"
void = { version = "1.0", default-features = false }

# STM32F4 HAL
stm32f4xx-hal = { version = "0.21", features = ["stm32f407"] }

# 数据结构
heapless = { version = "0.7", features = ["serde"] }
tinyvec = { version = "1.6", features = ["alloc"] }

# 序列化
serde = { version = "1.0", default-features = false, features = ["derive"] }
postcard = { version = "1.0", features = ["heapless"] }

# 时间处理
fugit = "0.3"
embedded-time = "0.12"

# 数学运算
libm = "0.2"
micromath = { version = "2.0", features = ["vector"] }
num-traits = { version = "0.2", default-features = false }

# 调试和日志
panic-halt = "0.2"
rtt-target = { version = "0.4", optional = true }
cortex-m-log = { version = "0.8", features = ["log-integration"], optional = true }
log = "0.4"

# 同步和原子操作
atomic-polyfill = "1.0"
critical-section = "1.1"
portable-atomic = { version = "1.0", features = ["critical-section"] }

[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = "s"
overflow-checks = true
lto = false
panic = "abort"

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = "s"
overflow-checks = false
panic = "abort"
strip = true

# 内存配置
[package.metadata.memory]
ram_start = 0x20000000
ram_size = "128K"
flash_start = 0x08000000
flash_size = "1024K"
stack_size = "4K"
heap_size = "16K"

# 控制器配置
[package.metadata.controller]
max_io_points = 64
max_programs = 8
max_timers = 16
scan_cycle_ms = 10
max_alarms = 32

# 构建配置
[package.metadata.build]
target = "thumbv7em-none-eabihf"
runner = "probe-rs run --chip STM32F407VGTx"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=--nmagic",
]

[features]
default = ["basic-io", "timers", "debug"]
basic-io = []
timers = []
counters = []
analog-io = []
communication = []
debug = ["rtt-target", "cortex-m-log"]

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

# Examples and tests will be added when files are created