[package]
name = "environmental-monitor"
version = "0.1.0"
edition = "2021"
authors = ["Embedded Developer <dev@example.com>"]
description = "Advanced environmental monitoring system with multiple sensors"

[dependencies]
# 核心依赖
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
nb = "1.0"

# STM32F4 HAL
stm32f4xx-hal = { version = "0.14", features = ["stm32f401", "rt"] }

# 传感器驱动
bmp280 = "0.2"
sht3x = "0.2"
tsl2561 = "0.1"
mhz19 = "0.1"
pms7003 = "0.1"

# 数学和信号处理
libm = "0.2"
heapless = "0.7"
micromath = "2.0"
nalgebra = { version = "0.32", default-features = false, features = ["libm"] }

# 时间管理
systick-monotonic = "1.0"
fugit = "0.3"

# 数据序列化和存储
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-json-core = "0.4"
postcard = "1.0"

# Flash存储
w25q = "0.1"
embedded-storage = "0.3"

# 通信协议
embedded-hal = "0.2"
modbus = { version = "0.1", default-features = false }

# 显示
ssd1306 = "0.7"
embedded-graphics = "0.7"

# 网络通信 (可选)
esp-wifi = { version = "0.1", optional = true }
smoltcp = { version = "0.9", default-features = false, optional = true }

# 加密和安全
aes = { version = "0.8", default-features = false, optional = true }
sha2 = { version = "0.10", default-features = false, optional = true }

[features]
default = ["display", "data-logging", "wireless"]
display = ["ssd1306", "embedded-graphics"]
data-logging = ["w25q", "embedded-storage"]
wireless = ["esp-wifi", "smoltcp"]
security = ["aes", "sha2"]
advanced-analytics = ["nalgebra"]
modbus-support = ["modbus"]

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "calibration"
path = "src/calibration.rs"

[[bin]]
name = "data-export"
path = "src/data_export.rs"

[profile.dev]
debug = true
opt-level = "s"
overflow-checks = true

[profile.release]
debug = true
lto = true
opt-level = "s"
codegen-units = 1

# 目标平台配置
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "arm-none-eabi-gdb"
rustflags = [
  "-C", "linker=arm-none-eabi-ld",
  "-C", "link-arg=-Tlink.x",
]

# 内存配置
[target.thumbv7em-none-eabihf]
runner = "arm-none-eabi-gdb"
rustflags = [
  "-C", "linker=arm-none-eabi-ld",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=--nmagic",
]