[package]
name = "display-controller"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "嵌入式显示控制器 - 支持OLED、LCD和电子纸显示"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yourusername/display-controller"
readme = "README.md"
keywords = ["embedded", "display", "oled", "lcd", "epaper", "graphics"]
categories = ["embedded", "graphics", "hardware-support"]

[dependencies]
# 核心依赖
embedded-hal = "1.0"
nb = "1.1"
heapless = "0.8"
embedded-graphics = "0.8"
embedded-graphics-core = "0.4"

# 显示驱动
ssd1306 = "0.8"  # OLED显示驱动
st7735-lcd = "0.10"  # LCD显示驱动
epd-waveshare = "0.5"  # 电子纸显示驱动

# 字体支持
embedded-graphics-profont = "0.8"
u8g2-fonts = "0.4"

# 图形和颜色
embedded-graphics-simulator = { version = "0.5", optional = true }
tinybmp = "0.5"
tinytga = "0.5"

# 数学和工具
libm = "0.2"
micromath = "2.0"

# 异步支持（可选）
embedded-hal-async = { version = "1.0", optional = true }
futures = { version = "0.3", default-features = false, optional = true }

# 日志
log = "0.4"

[dev-dependencies]
embedded-graphics-simulator = "0.5"
sdl2 = "0.36"

[features]
default = ["oled", "lcd"]

# 显示类型支持
oled = ["ssd1306"]
lcd = ["st7735-lcd"]
epaper = ["epd-waveshare"]

# 高级功能
advanced-graphics = ["tinybmp", "tinytga"]
animation = []
touch-support = []

# 异步支持
async = ["embedded-hal-async", "futures"]

# 开发和测试
simulator = ["embedded-graphics-simulator"]

[[example]]
name = "oled_demo"
required-features = ["oled"]

[[example]]
name = "lcd_demo"
required-features = ["lcd"]

[[example]]
name = "epaper_demo"
required-features = ["epaper"]

[[example]]
name = "graphics_demo"
required-features = ["advanced-graphics"]

[profile.release]
opt-level = "s"  # 优化代码大小
lto = true       # 链接时优化
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 1    # 开发时适度优化
debug = true

# 文档配置
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]