[package]
name = "wireless-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
nb = "1.0"
embedded-hal = "0.2"
stm32f4xx-hal = { version = "0.14", features = ["stm32f401", "rt"] }
heapless = "0.7"
rtic = { version = "2.0", features = ["thumbv7-backend"] }
esp-wifi = { version = "0.4", features = ["esp32c3"] }
embedded-svc = "0.25"

[[bin]]
name = "main"
path = "src/main.rs"

[profile.dev]
debug = true
opt-level = "s"

[profile.release]
debug = true
lto = true
opt-level = "s"