[package]
name = "digital-io-example"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
description = "Digital I/O control examples for embedded systems"
license = "MIT OR Apache-2.0"
repository = "https://github.com/your-username/embedded-development"
edition = "2021"

[dependencies]
# Core embedded dependencies
embedded-hal = "1.0"
nb = "1.1"
cortex-m = "0.7"
cortex-m-rt = "0.7"

# Debug and logging
defmt = "0.3"
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }

# Data structures
heapless = "0.8"
bitfield = "0.14"

# Time handling
fugit = "0.3"

# Math libraries
micromath = "2.0"
libm = "0.2"

# Synchronization
critical-section = "1.1"
atomic-polyfill = "1.0"

# State machine
smlang = "0.6"

# Platform-specific HAL dependencies
[target.'cfg(feature = "stm32f4xx")'.dependencies]
stm32f4xx-hal = { version = "0.20", features = ["rt", "stm32f407"] }

[target.'cfg(feature = "esp32")'.dependencies]
esp32-hal = "0.17"

[target.'cfg(feature = "rp2040")'.dependencies]
rp2040-hal = "0.9"

[features]
default = ["stm32f4xx"]
stm32f4xx = []
esp32 = []
rp2040 = []

# Binary targets
[[bin]]
name = "basic"
path = "src/bin/basic.rs"

[[bin]]
name = "matrix-keypad"
path = "src/bin/matrix_keypad.rs"

[[bin]]
name = "led-matrix"
path = "src/bin/led_matrix.rs"

[[bin]]
name = "shift-register"
path = "src/bin/shift_register.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[profile.dev]
debug = 2
opt-level = "s"

[profile.release]
debug = 2
lto = true
opt-level = "z"

# Target configuration
[build]
target = "thumbv7em-none-eabihf"