[package]
name = "sensor-hub"
version = "0.1.0"
authors = ["Embedded Developer <dev@example.com>"]
edition = "2021"
description = "Multi-sensor data acquisition hub for STM32F4"
license = "MIT OR Apache-2.0"
repository = "https://github.com/example/sensor-hub"
keywords = ["embedded", "stm32", "sensors", "i2c", "spi"]
categories = ["embedded", "hardware-support"]

[workspace]
# Empty workspace to prevent conflicts with parent workspace

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
nb = "1.0"
heapless = "0.7"
embedded-hal = "0.2.7"
fugit = "0.3"

# 调试和日志支持
defmt = "0.3"
defmt-rtt = "0.4"

# 数学和算法支持
libm = "0.2"
micromath = "2.0"

# CRC计算
crc = "3.0"
shared-bus = "0.2"

[dependencies.stm32f4xx-hal]
version = "0.14"
features = ["stm32f401", "defmt"]

[[bin]]
name = "sensor-hub"
path = "src/main.rs"

[profile.dev]
debug = true
lto = false
opt-level = 1
overflow-checks = true
panic = "abort"

[profile.release]
debug = true
lto = true
opt-level = "s"
codegen-units = 1
panic = "abort"
strip = false
overflow-checks = false

# 功能特性
[features]
default = ["bmp280-sensor", "mpu6050-sensor", "flash-storage"]
bmp280-sensor = []
mpu6050-sensor = []
flash-storage = []
debug-output = []