[package]
name = "freertos_tasks"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
freertos-rust = "0.1"
stm32f4xx-hal = { version = "0.17", features = ["stm32f401", "rt"] }
heapless = "0.7"
nb = "1.0"
embedded-hal = "0.2"

[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
lto = false
opt-level = "s"
overflow-checks = true

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = true
opt-level = "s"
overflow-checks = false

[[bin]]
name = "freertos_tasks"
test = false
bench = false