[package]
name = "interrupt-handler"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
nb = "1.0"
embedded-hal = "0.2"
heapless = "0.7"

[dependencies.stm32f4xx-hal]
version = "0.14"
features = ["stm32f407", "rt"]

[[bin]]
name = "basic_timer_interrupt"
path = "src/basic_timer_interrupt.rs"

[[bin]]
name = "external_interrupt"
path = "src/external_interrupt.rs"

[[bin]]
name = "priority_management"
path = "src/priority_management.rs"

[[bin]]
name = "interrupt_latency"
path = "src/interrupt_latency.rs"