[package]
name = "sensor-hub"
version = "0.1.0"
edition = "2021"
authors = ["Embedded Developer"]
description = "Multi-sensor data collection hub using I2C and SPI"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
nb = "1.0"
heapless = "0.7"
embedded-hal = "0.2"

[dependencies.stm32f4xx-hal]
version = "0.14"
features = ["stm32f401", "rt"]

# 传感器驱动库
[dependencies.bmp280]
version = "0.3"
default-features = false

[dependencies.mpu6050]
version = "0.1"
default-features = false

[[bin]]
name = "sensor-hub"
path = "src/main.rs"

[profile.dev]
debug = true
lto = false
opt-level = 1

[profile.release]
debug = true
lto = true
opt-level = "s"
codegen-units = 1

# 目标平台配置
[build]
target = "thumbv7em-none-eabihf"

# 链接器配置
[target.thumbv7em-none-eabihf]
runner = "arm-none-eabi-gdb"
rustflags = [
  "-C", "linker=arm-none-eabi-ld",
  "-C", "link-arg=-Tlink.x",
]

# 功能特性
[features]
default = ["bmp280-sensor", "mpu6050-sensor", "flash-storage"]
bmp280-sensor = []
mpu6050-sensor = []
flash-storage = []
debug-output = []