[package]
name = "build-automation"
version = "0.1.0"
edition = "2021"
authors = ["Embedded Rust Developer <dev@example.com>"]
description = "Build automation example for embedded Rust deployment"
license = "MIT OR Apache-2.0"
repository = "https://github.com/example/embedded-development"

[dependencies]
# 嵌入式核心库
cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-hal = "1.0"
embedded-hal-nb = "1.0"
panic-halt = "0.2"

# STM32F4 HAL
stm32f4xx-hal = { version = "0.20", features = ["stm32f401", "rt"] }

# 实时操作系统
rtic = { version = "2.1", features = ["thumbv7-backend"] }

# 数据结构和工具
heapless = "0.8"
nb = "1.1"
void = "1.0"

# 序列化
serde = { version = "1.0", default-features = false, features = ["derive"] }
postcard = "1.0"

# 构建工具依赖
[build-dependencies]
cc = "1.0"
bindgen = "0.69"

[features]
default = ["std"]
std = []
release = ["opt-level-3"]
debug = ["opt-level-1"]
size-opt = ["opt-level-s"]

# 多个构建目标
[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "bootloader"
path = "src/bootloader.rs"

[[bin]]
name = "test-runner"
path = "src/test_runner.rs"

# 编译配置
[profile.dev]
opt-level = 1
debug = true
lto = false
codegen-units = 16
panic = "abort"

[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.size-opt]
inherits = "release"
opt-level = "s"
lto = "fat"

# 目标平台配置
[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip STM32F401RETx"

# 链接器配置
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

# 内存配置
[package.metadata.memory]
flash = { origin = "0x08000000", length = "512K" }
ram = { origin = "0x20000000", length = "96K" }

# 测试配置
[dev-dependencies]
embedded-test = "0.4"
defmt-test = "0.3"

# 文档配置
[package.metadata.docs.rs]
default-target = "thumbv7em-none-eabihf"
targets = ["thumbv7em-none-eabihf"]

# 构建脚本配置
[package.metadata.build]
pre-build = ["scripts/pre-build.sh"]
post-build = ["scripts/post-build.sh"]
clean = ["scripts/clean.sh"]

# CI/CD配置
[package.metadata.ci]
targets = [
    "thumbv7em-none-eabihf",
    "thumbv6m-none-eabi",
    "thumbv7m-none-eabi"
]
test-targets = ["x86_64-unknown-linux-gnu"]