[package]
name = "input-capture"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
nb = "1.0"
embedded-hal = "0.2"

[dependencies.stm32f4xx-hal]
version = "0.14"
features = ["stm32f407", "rt"]

[[bin]]
name = "frequency_counter"
path = "src/frequency_counter.rs"

[[bin]]
name = "pulse_width_measurement"
path = "src/pulse_width_measurement.rs"

[[bin]]
name = "ultrasonic_distance"
path = "src/ultrasonic_distance.rs"

[[bin]]
name = "encoder_reader"
path = "src/encoder_reader.rs"