[package]
name = "iot-gateway"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "IoT Gateway for embedded systems communication and data routing"
license = "MIT OR Apache-2.0"
repository = "https://github.com/your-username/iot-gateway"
keywords = ["embedded", "iot", "gateway", "communication", "no-std"]
categories = ["embedded", "network-programming", "hardware-support"]

[dependencies]
# 核心嵌入式依赖
cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-hal = "0.2"
nb = "1.0"

# 数据结构和集合
heapless = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-json-core = "0.5"

# 网络和通信协议
embedded-nal = "0.7"
smoltcp = { version = "0.10", default-features = false, features = [
    "proto-ipv4", 
    "proto-tcp", 
    "proto-udp", 
    "proto-dhcpv4",
    "socket-tcp",
    "socket-udp",
    "async"
]}

# MQTT 客户端
minimq = "0.8"

# HTTP 客户端/服务器
embedded-svc = { version = "0.26", features = ["http-client", "http-server"] }

# 加密和安全
aes = { version = "0.8", default-features = false }
sha2 = { version = "0.10", default-features = false }
hmac = { version = "0.12", default-features = false }

# 时间处理
fugit = "0.3"
chrono = { version = "0.4", default-features = false, features = ["serde"] }

# 错误处理
thiserror-no-std = "2.0"

# 日志
log = "0.4"
defmt = "0.3"

# 异步支持
embassy-executor = { version = "0.5", features = ["arch-cortex-m", "executor-thread"] }
embassy-time = { version = "0.3", features = ["defmt"] }
embassy-sync = { version = "0.5", features = ["defmt"] }
embassy-futures = "0.1"

# 存储
embedded-storage = "0.3"
sequential-storage = "2.0"

[dev-dependencies]
panic-halt = "0.2"
cortex-m-semihosting = "0.5"

[features]
default = ["std"]
std = []
wifi = ["esp-wifi"]
ethernet = ["smoltcp/medium-ethernet"]
cellular = []
lora = []
zigbee = []
bluetooth = []

# 协议支持
mqtt = ["minimq"]
http = ["embedded-svc"]
coap = []
websocket = []

# 安全功能
tls = []
encryption = ["aes", "sha2", "hmac"]

# 调试功能
debug = ["log", "defmt"]
semihosting = ["cortex-m-semihosting"]

[profile.dev]
debug = true
opt-level = "s"

[profile.release]
debug = true
lto = true
opt-level = "z"
codegen-units = 1

[[example]]
name = "basic_gateway"
required-features = ["mqtt", "http"]

[[example]]
name = "wifi_gateway"
required-features = ["wifi", "mqtt"]

[[example]]
name = "ethernet_gateway"
required-features = ["ethernet", "http"]

[[example]]
name = "secure_gateway"
required-features = ["encryption", "tls"]