[package]
name = "low-power-sensor"
version = "0.1.0"
edition = "2021"
authors = ["Embedded Developer <dev@example.com>"]
description = "Low power sensor node with advanced power management"
license = "MIT OR Apache-2.0"
repository = "https://github.com/example/embedded-development"

[dependencies]
# 核心依赖
cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-hal = "0.2"
nb = "1.0"
panic-halt = "0.2"

# STM32F4 HAL
stm32f4xx-hal = { version = "0.14", features = ["rt", "stm32f401"] }

# 传感器驱动
bmp280 = "0.2"
sht3x = "0.2"
ds18b20 = "0.1"
one-wire-bus = "0.1"

# 数学和信号处理
libm = "0.2"
micromath = "2.0"
heapless = "0.7"

# 时间和延时
systick-monotonic = "1.0"
fugit = "0.3"

# 数据序列化
serde = { version = "1.0", default-features = false }
postcard = "1.0"

# 存储
embedded-storage = "0.3"
sequential-storage = "0.5"

# 通信
embedded-io = "0.4"

# 低功耗特性
rtcc = "0.3"

[features]
default = ["basic"]
basic = []
advanced = ["data-logging", "wireless"]
data-logging = []
wireless = []
debug = []

[[bin]]
name = "basic-low-power"
path = "src/basic_low_power.rs"

[[bin]]
name = "adaptive-sampling"
path = "src/adaptive_sampling.rs"

[[bin]]
name = "battery-monitor"
path = "src/battery_monitor.rs"

[[bin]]
name = "power-manager"
path = "src/power_manager.rs"

[profile.release]
debug = true
lto = true
opt-level = "s"
codegen-units = 1

[profile.dev]
debug = true
opt-level = 1

# 目标平台配置
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

# 链接器配置
[target.thumbv7em-none-eabihf]
runner = "probe-run --chip STM32F401RETx"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "target-cpu=cortex-m4",
  "-C", "target-feature=+fp-armv8d16",
]

# 内存配置
[package.metadata.memory]
ram_start = 0x20000000
ram_size = 96K
flash_start = 0x08000000
flash_size = 512K