[target.thumbv6m-none-eabi]
# Use probe-rs for flashing and debugging
runner = "probe-rs run --chip RP2040"

# Use the Tlink.x script from the cortex-m-rt crate
rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
# Set the default target for this project
target = "thumbv6m-none-eabi"

[env]
# Enable defmt logging
DEFMT_LOG = "debug"