[package]
name = "scheduler"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
nb = "1.0"
embedded-hal = "0.2"
heapless = "0.7"

[dependencies.stm32f4xx-hal]
version = "0.14"
features = ["stm32f407", "rt"]

[[bin]]
name = "cooperative_scheduler"
path = "src/cooperative_scheduler.rs"

[[bin]]
name = "preemptive_scheduler"
path = "src/preemptive_scheduler.rs"

[[bin]]
name = "priority_scheduler"
path = "src/priority_scheduler.rs"

[[bin]]
name = "real_time_scheduler"
path = "src/real_time_scheduler.rs"