[package]
name = "secure-bootloader"
version = "0.1.0"
edition = "2021"

[dependencies]
# 核心依赖
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
nb = "1.0"

# STM32F4 HAL
stm32f4xx-hal = { version = "0.16", features = ["stm32f407", "rt", "usb_fs"] }

# 数学和信号处理
libm = "0.2"
micromath = "2.0"
num-traits = { version = "0.2", default-features = false }

# 时间和延时
embedded-time = "0.12"

# 数据序列化和存储
heapless = { version = "0.8", features = ["serde"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
postcard = "1.0"

# 通信协议
embedded-hal = "0.2"

# 显示和用户界面
embedded-graphics = "0.8"
ssd1306 = "0.8"

# 加密和安全
sha2 = { version = "0.10", default-features = false }
hmac = { version = "0.12", default-features = false }
aes = { version = "0.8", default-features = false }
rsa = { version = "0.9", default-features = false, features = ["sha2"] }
rand_core = { version = "0.6", default-features = false }
signature = { version = "2.0", default-features = false }
pkcs1 = { version = "0.7", default-features = false }
pkcs8 = { version = "0.10", default-features = false }
ed25519-dalek = { version = "2.0", default-features = false, features = ["rand_core"] }

# 滤波和控制算法
pid = "4.0"

# Flash存储
embedded-storage = "0.3"
embedded-storage-async = "0.4"

# 实时任务调度
rtic = { version = "2.0", features = ["thumbv7-backend"] }
rtic-time = "1.0"
rtic-monotonics = { version = "1.0", features = ["cortex-m-systick"] }

# 日志和调试
defmt = "0.3"
defmt-rtt = "0.4"

# CRC计算
crc = "3.0"

# UUID生成
uuid = { version = "1.0", default-features = false }

# 引导加载器特定
bootloader-support = "0.1"

[features]
default = []
debug = ["defmt", "defmt-rtt"]
secure-boot = []
encrypted-firmware = []
rollback-protection = []

[[bin]]
name = "bootloader"
path = "src/main.rs"

[[bin]]
name = "firmware_updater"
path = "src/firmware_updater.rs"

[[bin]]
name = "secure_storage"
path = "src/secure_storage.rs"

[[bin]]
name = "crypto_engine"
path = "src/crypto_engine.rs"

[[bin]]
name = "signature_verifier"
path = "src/signature_verifier.rs"

[profile.dev]
debug = true
opt-level = 1

[profile.release]
debug = false
opt-level = "s"
lto = true
codegen-units = 1

# 目标平台配置
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F407VGTx"

# 链接器配置
[target.thumbv7em-none-eabihf]
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=-Tmemory.x",
]

# 内存配置
[package.metadata.memory]
flash = "1024K"
ram = "128K"

# 引导加载器内存布局
[package.metadata.bootloader]
bootloader_size = "64K"
application_start = "0x08010000"
application_size = "960K"

# RTIC配置
[package.metadata.rtic]
backend = "thumbv7-backend"