[package]
name = "multi-sensor"
version = "0.1.0"
edition = "2021"

[dependencies]
# 核心依赖
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
nb = "1.0"

# STM32F4 HAL
stm32f4xx-hal = { version = "0.14", features = ["stm32f401", "rt"] }

# 传感器驱动
bmp280 = "0.2"
mpu6050 = "0.2"
hdc1080 = "0.1"
tsl2561 = "0.1"

# 数学和数据处理
libm = "0.2"
heapless = "0.7"
micromath = "2.0"

# 时间管理
systick-monotonic = "1.0"
fugit = "0.3"

# 数据序列化
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-json-core = "0.4"
postcard = "1.0"

# 存储
w25q = "0.1"

# 通信
embedded-hal = "0.2"

[features]
default = ["data-logging", "wireless"]
data-logging = []
wireless = []
calibration = []
advanced-filtering = []
power-management = []

[[bin]]
name = "environmental-monitor"
path = "src/environmental_monitor.rs"

[[bin]]
name = "motion-tracker"
path = "src/motion_tracker.rs"

[[bin]]
name = "data-logger"
path = "src/data_logger.rs"

[profile.dev]
debug = true
opt-level = "s"

[profile.release]
debug = true
lto = true
opt-level = "s"

# 目标平台配置
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "arm-none-eabi-gdb"
rustflags = [
  "-C", "linker=arm-none-eabi-ld",
  "-C", "link-arg=-Tlink.x",
]