[package]
name = "rtic-basic"
version = "0.1.0"
edition = "2021"
authors = ["Embedded Rust Tutorial"]
description = "RTIC基础示例 - 多任务LED控制和按键处理"
keywords = ["embedded", "stm32f4", "rtic", "rtos", "real-time"]
categories = ["embedded", "hardware-support"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rtic-rs/cortex-m-rtic"

[[bin]]
name = "rtic-basic"
path = "src/main.rs"

[dependencies]
# RTIC框架
rtic = { version = "2.0", features = ["thumbv7-backend"] }
rtic-monotonics = { version = "1.0", features = ["cortex-m-systick"] }

# 核心嵌入式库
cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-hal = "0.2"
nb = "1.0"
panic-halt = "0.2"

# STM32F4 HAL库
stm32f4xx-hal = { version = "0.14", features = ["stm32f407", "rt"] }

# 调试和日志
rtt-target = { version = "0.3", features = ["cortex-m"] }
cortex-m-log = { version = "0.8", features = ["log-integration"] }
log = "0.4"

# 实用工具
heapless = "0.7"
fugit = "0.3"

[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = 1
overflow-checks = true

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = false
panic = "abort"

[profile.dev.package."*"]
codegen-units = 1
opt-level = 2

[profile.release.package."*"]
codegen-units = 1
opt-level = 3