# Cargo配置文件 - 优化编译性能和rust-analyzer体验

[build]
# 针对macOS优化的链接器配置
rustflags = []

# 目标配置
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=--nmagic",
]

# 优化编译缓存
[cargo-new]
vcs = "none"  # 不自动初始化git

# 网络配置
[net]
retry = 2
git-fetch-with-cli = true

# 注册表配置
[registry]
default = "crates-io"

# 源替换 - 可选，用于加速依赖下载
# [source.crates-io]
# replace-with = "ustc"
# 
# [source.ustc]
# registry = "https://mirrors.ustc.edu.cn/crates.io-index"