[package]
name = "ultrasonic-sensor"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
nb = "1.0"
embedded-hal = "0.2"
stm32f4xx-hal = { version = "0.14", features = ["stm32f401"] }
heapless = "0.7"
micromath = "2.0"

[[bin]]
name = "single_sensor"
path = "src/single_sensor.rs"

[[bin]]
name = "multi_sensor"
path = "src/multi_sensor.rs"

[[bin]]
name = "obstacle_avoidance"
path = "src/obstacle_avoidance.rs"

[[bin]]
name = "distance_mapping"
path = "src/distance_mapping.rs"

[profile.release]
debug = true
lto = true