[target.thumbv7em-none-eabihf]
rustflags = [
    "-C", "link-arg=-T${CARGO_MANIFEST_DIR}/memory.x",
    "-C", "link-arg=--nmagic",
    "-C", "linker=rust-lld",
]

[env]
# 确保cortex-m-rt库能找到memory.x文件
RUST_TARGET_PATH = "${CARGO_MANIFEST_DIR}"