[package]
name = "rtos-kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
nb = "1.0"
embedded-hal = "0.2"
stm32f4xx-hal = { version = "0.14", features = ["stm32f401"] }
heapless = "0.7"
micromath = "2.0"
linked_list_allocator = "0.10"

[[bin]]
name = "basic_kernel"
path = "src/basic_kernel.rs"

[[bin]]
name = "task_scheduler"
path = "src/task_scheduler.rs"

[[bin]]
name = "memory_manager"
path = "src/memory_manager.rs"

[[bin]]
name = "ipc_system"
path = "src/ipc_system.rs"

[profile.release]
debug = true
lto = true