[package]
name = "basic_rtic_example"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
rtic = { version = "2.0", features = ["thumbv7-backend"] }
stm32f4xx-hal = { version = "0.14", features = ["stm32f401"] }
panic-halt = "0.2"
heapless = "0.7"
nb = "1.0"

[dependencies.dwt-systick-monotonic]
version = "1.1"

[[bin]]
name = "main"
path = "src/main.rs"

[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = "s"
overflow-checks = true

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = true
opt-level = "s"
overflow-checks = false

# cargo build/run
[profile.dev.package."*"]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = "s"
overflow-checks = true

# cargo test
[profile.test]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = "s"
overflow-checks = true

# cargo test --release
[profile.bench]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = true
opt-level = "s"
overflow-checks = false