[package]
name = "dma-sampling"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
nb = "1.0"
embedded-hal = "0.2"
heapless = "0.7"
micromath = "2.0"

[dependencies.stm32f4xx-hal]
version = "0.14"
features = ["rt", "stm32f407"]

[[bin]]
name = "basic_dma"
path = "src/bin/basic_dma.rs"

[[bin]]
name = "circular_buffer"
path = "src/bin/circular_buffer.rs"

[[bin]]
name = "dual_buffer"
path = "src/bin/dual_buffer.rs"

[[bin]]
name = "high_speed_sampling"
path = "src/bin/high_speed_sampling.rs"

[[bin]]
name = "multi_channel_dma"
path = "src/bin/multi_channel_dma.rs"

[profile.dev]
debug = true
opt-level = "s"

[profile.release]
debug = true
lto = true
opt-level = "s"