[package]
name = "multi-task-scheduler"
version = "0.1.0"
edition = "2021"
authors = ["Embedded Developer <dev@example.com>"]
description = "Multi-task scheduler implementation for RTOS integration"
license = "MIT OR Apache-2.0"
keywords = ["embedded", "rtos", "scheduler", "tasks", "real-time"]
categories = ["embedded", "concurrency"]

[dependencies]
# Core embedded dependencies
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"

# STM32F4 HAL
stm32f4xx-hal = { version = "0.19", features = ["stm32f407", "rt"] }

# RTOS frameworks
rtic = { version = "2.0", features = ["thumbv7-backend"] }
freertos-rust = { version = "0.1", optional = true }

# Data structures
heapless = "0.7"
nb = "1.0"
void = "1.0"

# Timing and monotonic
dwt-systick-monotonic = "1.1"
systick-monotonic = "1.0"

# Utilities
bitflags = "2.0"
embedded-hal = "0.2"

# Logging
log = "0.4"
rtt-target = "0.4"
rtt-log = "0.1"

[dev-dependencies]
cortex-m-semihosting = "0.5"

[features]
default = ["rtic-scheduler"]
rtic-scheduler = []
freertos-scheduler = ["freertos-rust"]
performance-monitoring = []
deadlock-detection = []
real-time-analysis = []

[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
lto = false
opt-level = "s"
overflow-checks = true

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = true
opt-level = "s"
overflow-checks = false

# Metadata for cargo-embed
[package.metadata.embed]
chip = "STM32F407VGTx"
protocol = "Swd"
speed = 4000

[package.metadata.embed.gdb]
enabled = true
gdb_connection_string = "localhost:3333"