[package]
name = "industrial-hmi"
version = "0.1.0"
edition = "2021"
authors = ["Embedded Developer <dev@example.com>"]
description = "Industrial Human Machine Interface for STM32F4 microcontroller"
license = "MIT OR Apache-2.0"
repository = "https://github.com/example/embedded-development"
readme = "README.md"

[dependencies]
# 核心依赖
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
nb = "1.0"

# STM32F4 HAL
stm32f4xx-hal = { version = "0.19", features = ["stm32f407", "rt", "usb_fs"] }

# 数学和信号处理
libm = "0.2"
micromath = "2.0"
heapless = "0.8"

# 时间和延时
embedded-time = "0.12"
fugit = "0.3"

# 数据序列化和存储
serde = { version = "1.0", default-features = false, features = ["derive"] }
postcard = "1.0"
embedded-storage = "0.3"

# 通信协议
embedded-hal = "1.0"
embedded-io = "0.6"

# 显示和用户界面
embedded-graphics = "0.8"
ssd1306 = "0.8"
ili9341 = "0.6"
st7789 = "0.7"
embedded-graphics-simulator = "0.5"

# 触摸屏支持
xpt2046 = "0.3"

# 网络通信
smoltcp = { version = "0.11", default-features = false, features = [
    "std", "log", "medium-ethernet", "proto-ipv4", "proto-tcp", "socket-tcp", "socket-udp"
] }

# 以太网驱动
stm32-eth = { version = "0.6", features = ["stm32f407"] }

# 加密和安全
aes = { version = "0.8", default-features = false }
sha2 = { version = "0.10", default-features = false }

# 滤波和控制算法
pid = "4.0"

# Flash存储
embedded-storage-async = "0.4"

# 实时任务调度
rtic = { version = "2.0", features = ["thumbv7-backend"] }
rtic-monotonics = { version = "1.0", features = ["cortex-m-systick"] }

# 日志和调试
log = "0.4"
defmt = "0.3"
defmt-rtt = "0.4"

# CRC计算
crc = "3.0"

# 字体支持
embedded-graphics-core = "0.4"
profont = "0.7"

# 音频支持
pwm-pca9685 = "0.3"

[features]
default = ["std-features"]

# 标准功能特性
std-features = [
    "tft-display",
    "touch-screen",
    "ethernet",
    "modbus-tcp",
    "web-interface",
    "data-logging",
    "alarm-system",
    "trending"
]

# TFT显示屏
tft-display = ["ili9341", "st7789"]

# 触摸屏
touch-screen = ["xpt2046"]

# 以太网通信
ethernet = ["smoltcp", "stm32-eth"]

# Modbus TCP支持
modbus-tcp = ["ethernet"]

# Web界面
web-interface = ["ethernet"]

# 数据记录
data-logging = ["embedded-storage"]

# 报警系统
alarm-system = []

# 趋势图
trending = []

# 高级控制算法
advanced-control = ["pid"]

# 安全功能
security = ["aes", "sha2"]

# 音频报警
audio-alarm = ["pwm-pca9685"]

# 调试功能
debug = ["defmt", "defmt-rtt", "log"]

[[bin]]
name = "industrial_hmi"
path = "src/main.rs"

[[bin]]
name = "display_test"
path = "src/bin/display_test.rs"

[[bin]]
name = "touch_test"
path = "src/bin/touch_test.rs"

[[bin]]
name = "modbus_hmi_test"
path = "src/bin/modbus_hmi_test.rs"

[[bin]]
name = "web_hmi_test"
path = "src/bin/web_hmi_test.rs"

[[bin]]
name = "alarm_test"
path = "src/bin/alarm_test.rs"

[profile.dev]
debug = true
opt-level = "s"
lto = false
codegen-units = 1
incremental = false

[profile.release]
debug = false
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

# 目标平台配置
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F407VGTx"

# 链接器配置
[target.thumbv7em-none-eabihf]
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

# 内存配置
[package.metadata.memory]
flash = "1024K"
ram = "128K"

# RTIC配置
[package.metadata.rtic]
backend = "thumbv7-backend"